- tools/gps-replay.py
Adds command line options to gps-replay.py for testing and debugging.
> Add command line options to gps-replay

- br-webui/index.js
- br-webui/views/network.liquid
> Add cpu status in network

- br-webui/index.js
- br-webui/views/system.liquid
> Add reboot pixhawk button

- br-webui/index.js
> Add IP address in Wifi Status

- tools/px_uploader.py
> Remove unplug messages

- br-webui/index.js
- br-webui/views/network.liquid
- scripts/set_default_client_ip.sh
- tools/cmdline.txt
> Add dhcp client configuration

- tools/underwater-gps.py
> underwater-gps: Update demo server address and port

- tools/underwater-gps.py
> underwater-gps: Change prints to work with python3

- br-webui/_includes/header.liquid
- br-webui/index.js
There is an issue where header.liquid is not getting the socket.emit from index.js. Please review and give suggestions.
> Fix #15: Add error reporting

- br-webui/index.js
- br-webui/views/system.liquid
Added status of processes to the system page of companion web interface.
> fix #108   

- params/mavproxy.param.default
> mavproxy: Use mavlink2 as default

- .companion.rc
- scripts/post-update.sh
- tools/PingBootloader.py
- tools/ping1d_mavlink_driver.py
- tools/ping_enumerator.py
This changes the companions scripts to install 'brping' from pip and to use it.
Fix #169
> install bluerobotics-ping with pip

- tools/underwater-gps.py
This sends a NMEA stream to QGC port 14401.
Wait until https://github.com/mavlink/qgroundcontrol/pull/7087 is merged before merging this.
> underwater-gps.py: add support for nmea output to port 14401

- scripts/update.sh
Fix bluerobotics/companion-private#5
> update: Stash everything before hard reset

- tools/flash_px4.py
> Change download link for development firmware

- br-webui/index.js
- params/100.autopilot.rules
- params/mavproxy.param.default
- scripts/post-update.sh
- scripts/setup.sh
- tools/flashPXParameters.py
- tools/flash_px4.py
- tools/telem.py
> Add udev rules to support both PixHawk firmwares

- br-webui/views/system.liquid
> system: Update Ardusub version after firmware changes

- br-webui/views/git.liquid
> Visual improvements to git page

- params/mavproxy.param.default
> mavproxy.param.default: Add udpin for ping-viewer

- tools/audio.py
- tools/comm_router.py
- tools/endpoint.py
- tools/flashPXParameters.py
- tools/flash_px4.py
- tools/nmea-receiver.py
- tools/px_uploader.py
- tools/query-screen.py
- tools/query-udevadm.py
- tools/streamer.py
- tools/telem.py
- tools/underwater-gps.py
Trailing spaces are bad and we should feel bad
> Remove trailing spaces

- tools/underwater-gps.py
> Fix underwater-gps with incorrect payloads

- br-webui/views/network.liquid
DHCP server works with multiple clients
Fix #280 
> views: network: Update info message

- release-notes.txt
> release-notes: Add 0.0.18

- .companion.rc
- scripts/detect-navigator.sh
- scripts/post-update.sh
- scripts/start-ardusub-linux.sh
Add navigator support for raspberry pi 3 and ardusub linux
> Add navigator support and ardusub linux

- params/dhcpd-server.conf
- params/gstreamer2.param.default
- scripts/post-update.sh
- scripts/start_audio.sh
- tools/underwater-gps.py
Video broadcast is resulting in a weird behavior, making routers unstable and poor performance.
> Revert video broadcast and dhcp server

- configuration/swagger.js
- docs/api.yaml
- docs/camera.yaml
- docs/mavproxy.yaml
- docs/network.yaml
- docs/pixhawk.yaml
- docs/system.yaml
> docs: Move to openapi 3.0.0

- scripts/post-update.sh
> post-update: Add reboot after update

- release-notes.txt
> release-notes: Add 0.0.19

- .companion.rc
- br-webui/index.js
- br-webui/package.json
- br-webui/views/network.liquid
- scripts/post-update.sh
- services/network/main.py
- services/network/setup.py
- services/network/wpa_supplicant.py
This PR also allows utf-8 chars in ssid
Fix #325 
> Add wifi service

- scripts/start_webui.sh
This requires password input from the user
> scripts: start_webui: Remove ssh-agent

- br-webui/index.js
The check for new versions fail since the lock file can exist
Fix #251 
> index: Remove lock files if they exist

- services/network/main.py
- services/network/wpa_supplicant.py
- Improve stability and add a couple of more checks to deal with failures in wpa_supplicant
How to test: Type a wrong password
> Improve network service 

- br-webui/index.js
Fmuv2 has a 1M flash limitation
> index.js: Use Pixhawk1 instead of fmuv2
